### ISSUE TITLE
Publishing failure via GitHub action

### ISSUE THREAD

**Issue by snazy** [SmartBear/swaggerhub-cli#290]
### Q&A (please complete the following information)
 - CLI version: 0.7.0 (0.6.5 was fine)
 - OS: Linux / Ubuntu 22.04 (standard GH hosted runner)
 - Node.js version: n/a (Docker)
 - SwaggerHub version if On-Premise: n/a

### Describe the bug you're encountering
After the bump of the Swaggerhub GitHub action from 0.6.5 to 0.7.0, publishing fails with the following exception. The call site looks like this:
```
    - name: Update SwaggerHub
      uses: smartbear/swaggerhub-cli@v0.7.0
      env:
        XDG_CONFIG_HOME: "/tmp"
        SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        SWAGGERHUB_URL: "https://api.swaggerhub.com"
      with:
        args: api:create projectnessie/nessie -f ${{ env.NESSIE_OPENAPI }} --published=publish --setdefault --visibility=public
```

### Error message

```
Run smartbear/swaggerhub-cli@v0.7.0
  with:
    args: api:create projectnessie/nessie -f api/model/build/nessie-openapi-0.55.0.yaml --published=publish --setdefault --visibility=public
  env:
    RELEASE_VERSION: 0.55.0
    GIT_TAG: nessie-0.55.0
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
    pythonLocation: /opt/hostedtoolcache/Python/3.8.16/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.16/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.16/x64
    Python[2](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:3).8.16/x6[4](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.16/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.16/x64/lib
    QUARKUS_UBER_JAR: ../build-artifacts/nessie-quarkus-0.[5](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:5)5.0-runner.jar
    CLI_UBER_JAR: ../build-artifacts/nessie-quarkus-cli-0.55.0-runner.jar
    QUARKUS_NATIVE_BINARY: ../build-artifacts/nessie-quarkus-0.55.0-runner
    GC_EXEC: gc/gc-shell/build/executable/nessie-gc
    NESSIE_OPENAPI: api/model/build/nessie-openapi-0.55.0.yaml
    NESSIE_HELM_CHART: nessie-helm-0.55.0.tgz
    NOTES_FILE: /tmp/tmp.HJOqe9dwL9/release-notes.md
    XDG_CONFIG_HOME: /tmp
    SWAGGERHUB_API_KEY: ***
    SWAGGERHUB_URL: https://api.swaggerhub.com
/usr/bin/docker run --name c0442bc59f1cb8ec24349a[6](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:6)08b1d23906c3ca_f90e8b --label 6c0442 --workdir /github/workspace --rm -e "RELEASE_VERSION" -e "GIT_TAG" -e "JAVA_HOME" -e "JAVA_HOME_11_X64" -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "QUARKUS_UBER_JAR" -e "CLI_UBER_JAR" -e "QUARKUS_NATIVE_BINARY" -e "GC_EXEC" -e "NESSIE_OPENAPI" -e "NESSIE_HELM_CHART" -e "NOTES_FILE" -e "XDG_CONFIG_HOME" -e "SWAGGERHUB_API_KEY" -e "SWAGGERHUB_URL" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/cli/gh_entrypoint.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nessie/nessie":"/github/workspace" [REDACTED] api:create projectnessie/nessie -f api/model/build/nessie-openapi-0.55.0.yaml --published=publish --setdefault --visibility=public
/cli/node_modules/@oclif/core/lib/command.js:45
            delete this.baseFlags?.json;
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:2[7](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:7))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:[8](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:8)63:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:1[9](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:9))
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/cli/node_modules/@oclif/core/lib/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:10)27:10)
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-[11](https://github.com/projectnessie/nessie/actions/runs/4611561895/jobs/8151401644#step:21:11)-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by barryadk** [comment]
Updating to version 0.7.1 should resolve the issue for you.

**Comment by snazy** [comment]
:+1:
Thanks for the quick response and release!
